### PR TITLE
add test for Proposals.RStagger

### PR DESCRIPTION
**Pull request by SaranjeetKaur**

### CODE REVIEW

**Comment by cpfiffer** [comment]
These two proposals (#39 and #40) should not be added as separate PRs (and these should be closed). The changes inside #39 and #40 need to be included in your original PR #38. Each PR is a full "package" of changes -- it includes new features and tests all together.

Do you know how to add commits to existing branches? It's fine if not -- though you may need to spend a little time getting up to speed on Git. How are you actually editing your code and making commits?

**Comment by SaranjeetKaur** [comment]
> These two proposals (#39 and #40) should not be added as separate PRs (and these should be closed). The changes inside #39 and #40 need to be included in your original PR #38. Each PR is a full "package" of changes -- it includes new features and tests all together.
> 
> Do you know how to add commits to existing branches? It's fine if not -- though you may need to spend a little time getting up to speed on Git. How are you actually editing your code and making commits?

okay i shall close the PRs #39 and #40 and include these changes in PR #38. i will learn more about Git.. i am editing my code and commiting via GitHub

**Comment by cpfiffer** [comment]
> i am editing my code and commiting via GitHub

Yeah, I would advise not doing that. GitHub is not meant for full development like this. You can't test any of your code as you write it. Get in the habit of using a real editor like VS Code, Atom, Vim, Emacs or something that is actually built for development. You should also be using Git through the command line or the equivalent of VS Code's easy Git tool.

**Comment by SaranjeetKaur** [comment]
ok.. have used VS Code (also a bit of Atom) earlier, so shall switch to it,
also am learning about Git (this is a material i'm referring to:
https://git-scm.com/book/en/v2  ).
Haven't tried VS Code's Git tool yet, good to know about it! will
familiarize myself with it..

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
